name: corunha_guide
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^0.13.6
  firebase_core: ^0.4.0
  firebase_auth: ^0.16.1
  firebase_storage:
    git:
      url: git://github.com/danysz/flutterfire.git
      ref: master
      path: packages/firebase_storage  
  google_sign_in: ^4.0.1+1
  flutter_bloc: ^0.11.0
  equatable: ^0.2.0
  meta: ^1.1.6
  font_awesome_flutter: ^8.4.0
  url_launcher: ^5.4.11
  expandable: ^4.1.4
  flutter_rating_bar: ^3.0.1+1
  flag: ^3.0.1
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - lib/lang/en.json
    - lib/lang/es.json
 
fonts:
  - family: Roboto
    fonts:
      - asset: fonts/Roboto-Bold.ttf
      - asset: fonts/Roboto-Medium.ttf
      - asset: fonts/Roboto-Regular.ttf
  
 
